use_frameworks!

target 'RYAlertController_Example' do
  pod 'RYAlertController', :path => '../'

  target 'RYAlertController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
